Do not use memory fs as communication channels in pandarallel
We are probably hitting some limit and receive:
   EOFError: Ran out of input
when shared memmory is used.